In [2]:
import random,time

In [3]:
import numpy as np
N_DOCS= 500000
DIM = 384
docs = []

for i in range(N_DOCS):
    vectors = []
    for j in range(DIM):
        vectors.append(random.random())
    docs.append(vectors)

def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))



In [4]:
# len(docs[0])

query= [random.random() for i in range(DIM)]
start = time.time()
for i in range(N_DOCS):
    cosine_similarity(query, docs[i])
print(time.time() - start)

17.248687028884888


In [94]:
# memory computations
# in case of simplke list 100 documents * 384 dimensions * 8 bytes = 1.6 MB

docs_np= np.array(docs,dtype=np.float32)
query_np= np.array(query,dtype=np.float32)
results = []
start = time.time()
for i in range(N_DOCS):
    result = cosine_similarity(query_np, docs_np[i])
    results.append(result)
print(time.time() - start)

0.9913909435272217


### Why so fast?
1. **Python loops are interpreted** — every `x*y` does type-checking + object overhead
2. **NumPy runs compiled C loops** over raw memory
3. **Contiguous memory + SIMD** — CPU crunches multiple floats per instruction
4. **`@` calls BLAS** — decades-optimized linear algebra libraries

In [17]:
emb = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]],dtype=np.float16)

In [18]:
emb.shape # 3 vectors of 3 dimensions
emb.dtype
emb.nbytes

# 9*3*4 bytes

18

In [25]:
np.zeros((2,3)) # placeholer for results of computation
np.arange(0,10,2) # like range()
np.eye(3) # indentity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
rng = np.random.default_rng(seed = 42)
fake_embeddings =rng.normal(size=(1000, 384)).astype(np.float16)
weights = rng.normal(0,0.02,size=(768,768))
print(weights.shape, fake_embeddings.shape)

(768, 768) (1000, 384)


In [27]:
weights

array([[ 0.00887857,  0.00110225, -0.02640034, ..., -0.02804008,
        -0.03759766,  0.01629448],
       [ 0.01117758, -0.01886057,  0.02177145, ..., -0.00396047,
         0.00077956, -0.03090563],
       [-0.02251749,  0.01762229, -0.01862442, ..., -0.0051351 ,
         0.0143104 ,  0.00598157],
       ...,
       [-0.023123  , -0.02182115,  0.03040036, ...,  0.00683533,
         0.01309088,  0.04394885],
       [ 0.00431112, -0.02266811, -0.00545559, ...,  0.00102505,
         0.00445736,  0.01722014],
       [ 0.02661768, -0.04125598, -0.00725668, ...,  0.00187823,
        -0.01627447,  0.03133185]], shape=(768, 768))

In [28]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [33]:
x_test = x.reshape(6,4)

In [36]:
x_test.reshape(-1) # flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
W = rng.random((768,3072)).astype(np.float16)
X = rng.random((3072,768)).astype(np.float16)

In [86]:
# indexing, views vs copies
embeddings = rng.random((10, 4)).astype(np.float32)
original_value = embeddings[0, 0].copy()

subset = embeddings[:3]
subset[0,0]=999


In [87]:
subset

array([[9.9900000e+02, 4.2357746e-01, 9.9835509e-01, 9.3739581e-01],
       [2.2073671e-01, 5.3209764e-01, 1.5575875e-01, 4.4828373e-01],
       [3.1377172e-01, 4.7955853e-01, 7.5933647e-01, 3.8866407e-01]],
      dtype=float32)

In [88]:
embeddings

array([[9.9900000e+02, 4.2357746e-01, 9.9835509e-01, 9.3739581e-01],
       [2.2073671e-01, 5.3209764e-01, 1.5575875e-01, 4.4828373e-01],
       [3.1377172e-01, 4.7955853e-01, 7.5933647e-01, 3.8866407e-01],
       [9.5151013e-01, 8.5701287e-01, 2.4298935e-01, 5.9845144e-01],
       [2.0862342e-01, 2.6770216e-01, 1.1135638e-01, 2.7095374e-01],
       [4.5059200e-02, 9.2773801e-01, 5.1211995e-01, 6.6563398e-01],
       [5.3615057e-01, 2.9537043e-02, 4.7655478e-01, 5.0226408e-01],
       [3.8358173e-01, 3.8255069e-01, 5.5943310e-01, 3.4308171e-01],
       [4.6402916e-01, 6.4468615e-02, 2.3392031e-01, 5.3999633e-01],
       [5.4110301e-01, 9.9713874e-01, 7.6223391e-01, 1.9460320e-01]],
      dtype=float32)

In [89]:
original_value

np.float32(0.868683)

In [91]:
confidences = np.array([0.91, 0.45, 0.88, 0.12, 0.95, 0.60])
preds       = np.array([  1,    0,    1,    1,    0,    1 ])

mask = confidences > 0.8
print(mask
)
print(preds[mask])

[ True False  True False  True False]
[1 1 0]


In [92]:
labels = np.where(confidences > 0.8,"POSITIVE", "NEGATIVE")
labels

array(['POSITIVE', 'NEGATIVE', 'POSITIVE', 'NEGATIVE', 'POSITIVE',
       'NEGATIVE'], dtype='<U8')

In [95]:
results

[np.float32(0.758189),
 np.float32(0.75204575),
 np.float32(0.7634138),
 np.float32(0.7513342),
 np.float32(0.7422683),
 np.float32(0.75835943),
 np.float32(0.7435173),
 np.float32(0.75267434),
 np.float32(0.7204901),
 np.float32(0.7343192),
 np.float32(0.7523733),
 np.float32(0.77004164),
 np.float32(0.7736571),
 np.float32(0.7740351),
 np.float32(0.75702125),
 np.float32(0.7601685),
 np.float32(0.76085234),
 np.float32(0.7395647),
 np.float32(0.7546061),
 np.float32(0.74743545),
 np.float32(0.7577359),
 np.float32(0.739214),
 np.float32(0.76578563),
 np.float32(0.759154),
 np.float32(0.75670314),
 np.float32(0.76191086),
 np.float32(0.77362466),
 np.float32(0.7716694),
 np.float32(0.7509814),
 np.float32(0.74458927),
 np.float32(0.7541515),
 np.float32(0.7623467),
 np.float32(0.77071416),
 np.float32(0.7617246),
 np.float32(0.744713),
 np.float32(0.7505454),
 np.float32(0.7666302),
 np.float32(0.7491733),
 np.float32(0.7366723),
 np.float32(0.7451814),
 np.float32(0.74202),
 np.float

In [98]:
sims = np.array([0.2, 0.9, 0.1, 0.75, 0.88])
sims.argmax()


np.int64(1)

In [ ]:
sims.argsort() 
# 10 Million vectors --> 0(nlogn)
#argpartition - give you best match 

array([2, 0, 3, 4, 1])

In [108]:
# broadcasting
emb = rng.random((1000, 384)).astype(np.float32)
mean = emb.mean(axis=0)
centred = emb - mean # (1000,384) - (384,)
print(centred)

[[-0.02823189 -0.19982877  0.21061856 ... -0.34557003  0.31985328
   0.50352705]
 [-0.47692752  0.44544488 -0.5006284  ... -0.0793362   0.14692876
  -0.13210946]
 [-0.13983795  0.20563799 -0.4570307  ...  0.34603238 -0.31261873
   0.47902358]
 ...
 [-0.24612062  0.46884066  0.32883424 ... -0.29930258 -0.0998798
   0.2793042 ]
 [-0.4030961   0.41752934  0.30732995 ...  0.23607194  0.41357353
   0.21270376]
 [ 0.09406891  0.16811782  0.11356986 ...  0.0241611  -0.12683177
  -0.28117847]]


In [109]:
row_mean = emb.mean(axis=1) 

try:
    centred = emb - row_mean # (1000,384) - (1000,)
except ValueError as e:
    print(e)
    

operands could not be broadcast together with shapes (1000,384) (1000,) 


In [110]:
# the fix
row_mean = emb.mean(axis=1)
centred = emb - row_mean[:, np.newaxis]
print(centred)



[[-0.02147159 -0.18457097  0.23979053 ... -0.34918508  0.33359608
   0.503603  ]
 [-0.4956961   0.4351738  -0.49698532 ... -0.10848013  0.13514268
  -0.15756238]
 [-0.1190421   0.23493135 -0.4138232  ...  0.35645288 -0.28484038
   0.4931351 ]
 ...
 [-0.23166503  0.49179375  0.3657015  ... -0.29522234 -0.07844171
   0.28707546]
 [-0.41447645  0.4146465   0.31836128 ...  0.21431625  0.4091757
   0.19463909]
 [ 0.10192674  0.18447316  0.14383936 ...  0.02164358 -0.11199144
  -0.28000498]]


In [112]:
row_mean

array([0.48522434, 0.5107532 , 0.47118878, 0.48317108, 0.51115483,
       0.50845057, 0.47848022, 0.4997162 , 0.5102924 , 0.48844716,
       0.5147671 , 0.52160484, 0.48094043, 0.52499336, 0.48750225,
       0.4971654 , 0.49092996, 0.5164277 , 0.4681354 , 0.5084126 ,
       0.49699673, 0.49327913, 0.52406013, 0.511566  , 0.50680274,
       0.51225996, 0.48663726, 0.5378769 , 0.510098  , 0.4889473 ,
       0.49982142, 0.51297885, 0.5058058 , 0.49645326, 0.48605224,
       0.48309192, 0.50632584, 0.49100247, 0.5030776 , 0.50724596,
       0.51980567, 0.4950951 , 0.49592724, 0.50875443, 0.47479412,
       0.49550995, 0.50909805, 0.5017949 , 0.48102728, 0.48431483,
       0.49562287, 0.49257222, 0.51273584, 0.50940895, 0.4834945 ,
       0.5049079 , 0.50025564, 0.49975458, 0.49693096, 0.52090114,
       0.48155618, 0.48425913, 0.4738103 , 0.50505704, 0.49987593,
       0.5077022 , 0.49181917, 0.50570685, 0.48703137, 0.4998027 ,
       0.46707645, 0.50616723, 0.5199249 , 0.5126113 , 0.52618

In [111]:
row_mean[:, np.newaxis]

array([[0.48522434],
       [0.5107532 ],
       [0.47118878],
       [0.48317108],
       [0.51115483],
       [0.50845057],
       [0.47848022],
       [0.4997162 ],
       [0.5102924 ],
       [0.48844716],
       [0.5147671 ],
       [0.52160484],
       [0.48094043],
       [0.52499336],
       [0.48750225],
       [0.4971654 ],
       [0.49092996],
       [0.5164277 ],
       [0.4681354 ],
       [0.5084126 ],
       [0.49699673],
       [0.49327913],
       [0.52406013],
       [0.511566  ],
       [0.50680274],
       [0.51225996],
       [0.48663726],
       [0.5378769 ],
       [0.510098  ],
       [0.4889473 ],
       [0.49982142],
       [0.51297885],
       [0.5058058 ],
       [0.49645326],
       [0.48605224],
       [0.48309192],
       [0.50632584],
       [0.49100247],
       [0.5030776 ],
       [0.50724596],
       [0.51980567],
       [0.4950951 ],
       [0.49592724],
       [0.50875443],
       [0.47479412],
       [0.49550995],
       [0.50909805],
       [0.501

In [75]:
# W[0].T

In [76]:
# X[0].shape

In [77]:
# np.matmul(W[0].T, X[0])

In [78]:
# len(W.T[0])

In [ ]:
# y_pred = W.dot(X)

/var/folders/fq/kr6gv5l17pd4j572n0_n3f2c0000gn/T/ipykernel_55153/822111883.py:1: RuntimeWarning: overflow encountered in add
  y_pred = sum(W.dot(X))


In [79]:
# np.matmul(W, X)

In [80]:
# A = np.array([[1, 2], 
#               [3, 4]])
# B = np.array([[5, 6], 
#               [7, 8]])

# # Both lines produce the exact same matrix product
# result1 = np.matmul(A, B)

In [81]:
# result1

In [82]:
# x.reshape(2,7)

In [ ]:
# for i in range(0,10,2):
#     print(i)

0
2
4
6
8


In [83]:
# memory
# 100 * 384 * 4 

In [114]:
pip install sentence_transformers

  Using cached sentence_transformers-5.5.1-py3-none-any.whl.metadata (18 kB)
  Using cached transformers-5.10.2-py3-none-any.whl.metadata (33 kB)
  Using cached huggingface_hub-1.18.0-py3-none-any.whl.metadata (14 kB)
  Using cached torch-2.12.0-cp313-cp313-macosx_14_0_arm64.whl.metadata (31 kB)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
  Using cached pyyaml-6.0.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.4 kB)
  Using cached regex-2026.5.9-cp313-cp313-macosx_11_0_arm64.whl.metadata (40 kB)
  Using cached tokenizers-0.22.2-cp39-abi3-macosx_11_0_arm64.whl.metadata (7.3 kB)
  Using cached typer-0.26.7-py3-none-any.whl.metadata (16 kB)
  Using cached click-8.4.1-py3-none-any.whl.metadata (2.6 kB)
  Using cached filelock-3.29.1-py3-none-any.whl.metadata (2.0 kB)
  Using cached fsspec-2026.4.0-py3-none-any.whl.metadata (10 kB)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
  Using cached typer-0.25.1-py3-none-any.whl.metadata (15 kB)
  Us

In [115]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

text = "The quick brown fox jumps over the lazy dog"

vector = model.encode(text)

/Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/full_stack_ai_4th_may/test-env/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2635.01it/s]


In [117]:
len(vector) # 384 vector

384